name: Blackbird
options:
  bundleIdPrefix: com.deadjoe
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.0"
packages:
  FeedKit:
    url: https://github.com/nmdias/FeedKit
    from: 9.1.2
targets:
  Blackbird:
    type: application
    platform: iOS
    sources:
      - path: Blackbird
    dependencies:
      - package: FeedKit
    settings:
      base:
        INFOPLIST_FILE: Blackbird/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.deadjoe.blackbird
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    scheme:
      testTargets:
        - BlackbirdTests
  BlackbirdTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BlackbirdTests
    dependencies:
      - target: Blackbird
    settings:
      base:
        INFOPLIST_FILE: BlackbirdTests/Info.plist
